local Treesitter = {
  TSComment = { fg = C.green, style = "italic" },
  TSAnnotation = { fg = C.yellow },
  TSAttribute = { fg = C.cyan, style = "bold" },
  TSConstructor = { fg = C.cyan },
  TSType = { fg = C.cyan },
  TSTypeBuiltin = { fg = C.blue },
  TSConditional = { fg = C.blue, style = "italic" },
  TSException = { fg = C.purple, style = "italic" },
  TSInclude = { fg = C.purple, style = "italic" },
  TSKeywordReturn = { fg = C.purple, style = "italic" },
  TSKeyword = { fg = C.blue, style = "italic" },
  TSKeywordFunction = { fg = C.blue, style = "italic" },
  TSLabel = { fg = C.light_blue, style = "italic" },
  TSNamespace = { fg = C.cyan },
  TSRepeat = { fg = C.purple, style = "italic" },
  TSConstant = { fg = C.yellow },
  TSConstBuiltin = { fg = C.blue, style = "italic" },
  TSFloat = { fg = C.light_green },
  TSNumber = { fg = C.light_green },
  TSBoolean = { fg = C.blue, style = "italic" },
  TSCharacter = { fg = C.orange },
  TSError = { fg = C.error_red },
  TSFunction = { fg = C.yellow },
  TSFuncBuiltin = { fg = C.yellow, style = "bold" },
  TSMethod = { fg = C.yellow },
  TSConstMacro = { fg = C.cyan },
  TSFuncMacro = { fg = C.yellow, style = "italic" },
  TSVariable = { fg = C.light_blue },
  TSVariableBuiltin = { fg = C.light_blue, style = "bold" },
  TSProperty = { fg = C.light_blue },
  TSOperator = { fg = C.fg },
  TSField = { fg = C.light_blue },
  TSParameter = { fg = C.light_blue },
  TSParameterReference = { fg = C.light_blue },
  TSSymbol = { fg = C.light_blue },
  TSText = { fg = C.fg },
  TSPunctDelimiter = { fg = C.fg },
  TSTagDelimiter = { fg = C.gray },
  TSPunctBracket = { fg = C.fg },
  TSPunctSpecial = { fg = C.fg },
  TSString = { fg = C.orange },
  TSStringRegex = { fg = C.orange },
  TSStringEscape = { fg = C.yellow_orange },
  TSTag = { fg = C.blue },
  TSEmphasis = { style = "italic" },
  TSUnderline = { style = "underline" },
  TSTitle = { fg = C.blue, style = "bold" },
  TSLiteral = { fg = C.yellow_orange },
  TSURI = { fg = C.yellow_orange, style = "underline" },
  TSKeywordOperator = { fg = C.blue, style = "italic" },
  TSStructure = { fg = C.light_blue },
  TSStrong = { fg = C.yellow_orange },
  TSQueryLinterError = { fg = C.warning_orange },
}

return Treesitter
